//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petscare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int admin_ID { get; set; }
        public string admin_firstname { get; set; }
        public string admin_lastname { get; set; }
        public string admin_email { get; set; }
        public string admin_telephone { get; set; }
        public Nullable<int> admin_age { get; set; }
        public Nullable<bool> admin_gender { get; set; }
        public string admin_firstpassword { get; set; }
        public string admin_againpassword { get; set; }
    }
}
