//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petscare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointments
    {
        public int appointments_ID { get; set; }
        public Nullable<int> vets_ID { get; set; }
        public Nullable<int> pet_ID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string pet_name { get; set; }
    
        public virtual user_pets user_pets { get; set; }
        public virtual vets vets { get; set; }
    }
}
