//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petscare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contact_ID { get; set; }
        public string contact_userName { get; set; }
        public string contact_userSurname { get; set; }
        public string contact_email { get; set; }
        public string contact_message { get; set; }
    }
}
