//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petscare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class petscareEntities : DbContext
    {
        public petscareEntities()
            : base("name=petscareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<appointments> appointments { get; set; }
        public virtual DbSet<ownage_notice> ownage_notice { get; set; }
        public virtual DbSet<ownagenotices_pictures> ownagenotices_pictures { get; set; }
        public virtual DbSet<pet_gender> pet_gender { get; set; }
        public virtual DbSet<pets> pets { get; set; }
        public virtual DbSet<pets_appearance> pets_appearance { get; set; }
        public virtual DbSet<pets_breed> pets_breed { get; set; }
        public virtual DbSet<pets_breedpictures> pets_breedpictures { get; set; }
        public virtual DbSet<pets_species> pets_species { get; set; }
        public virtual DbSet<provinces> provinces { get; set; }
        public virtual DbSet<SliderImages> SliderImages { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_adress> user_adress { get; set; }
        public virtual DbSet<user_pets> user_pets { get; set; }
        public virtual DbSet<user_petsfeatures> user_petsfeatures { get; set; }
        public virtual DbSet<user_petspicture> user_petspicture { get; set; }
        public virtual DbSet<user_pictures> user_pictures { get; set; }
        public virtual DbSet<vaccine_calendar> vaccine_calendar { get; set; }
        public virtual DbSet<vets> vets { get; set; }
        public virtual DbSet<vets_adress> vets_adress { get; set; }
        public virtual DbSet<vets_pictures> vets_pictures { get; set; }
        public virtual DbSet<vaccine_status> vaccine_status { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
    }
}
