//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petscare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ownagenotices_pictures
    {
        public int notice_pictureID { get; set; }
        public string notice_picturesextension { get; set; }
        public Nullable<int> notice_ID { get; set; }
    
        public virtual ownage_notice ownage_notice { get; set; }
    }
}
