//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petscare.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class pets_breed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pets_breed()
        {
            this.ownage_notice = new HashSet<ownage_notice>();
            this.pets = new HashSet<pets>();
            this.pets_appearance = new HashSet<pets_appearance>();
            this.pets_species = new HashSet<pets_species>();
        }
    
        public int pets_breedID { get; set; }
        public string pets_breedname { get; set; }
        public Nullable<int> pets_breedpictureID { get; set; }
        public Nullable<int> pets_speciesID { get; set; }
        public string pets_breedpictureextension { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ownage_notice> ownage_notice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pets> pets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pets_appearance> pets_appearance { get; set; }
        public virtual pets_breedpictures pets_breedpictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pets_species> pets_species { get; set; }
    }
}
