//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petscare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pets()
        {
            this.pets_appearance = new HashSet<pets_appearance>();
        }
    
        public int pets_ID { get; set; }
        public Nullable<int> pets_speciesID { get; set; }
        public Nullable<int> pets_breedID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pets_appearance> pets_appearance { get; set; }
        public virtual pets_breed pets_breed { get; set; }
        public virtual pets_species pets_species { get; set; }
    }
}
