//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petscare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_pets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_pets()
        {
            this.appointments = new HashSet<appointments>();
            this.user_petsfeatures = new HashSet<user_petsfeatures>();
            this.user_petspicture = new HashSet<user_petspicture>();
            this.vaccine_calendar = new HashSet<vaccine_calendar>();
        }
    
        public int user_ID { get; set; }
        public int pet_ID { get; set; }
        public string pet_name { get; set; }
        public string pet_species { get; set; }
        public string pet_breed { get; set; }
        public Nullable<int> pet_petsfeaturesID { get; set; }
        public Nullable<int> pet_pictureID { get; set; }
        public Nullable<int> vets_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointments> appointments { get; set; }
        public virtual user user { get; set; }
        public virtual vets vets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_petsfeatures> user_petsfeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_petspicture> user_petspicture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vaccine_calendar> vaccine_calendar { get; set; }
    }
}
