//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petscare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_petspicture
    {
        public int pet_pictureID { get; set; }
        public Nullable<int> pet_ID { get; set; }
        public string pet_pictureextension { get; set; }
    
        public virtual user_pets user_pets { get; set; }
    }
}
