//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petscare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_pictures
    {
        public int user_picturesID { get; set; }
        public string user_pictureextension { get; set; }
        public Nullable<int> user_ID { get; set; }
    
        public virtual user user { get; set; }
    }
}
