//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petscare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaccine_calendar
    {
        public int vaccinecalendar_ID { get; set; }
        public Nullable<int> pet_ID { get; set; }
        public Nullable<int> vets_ID { get; set; }
        public Nullable<System.DateTime> vaccine_days { get; set; }
        public string vaccine_name { get; set; }
        public string vaccine_status { get; set; }
        public Nullable<int> vaccinestatus_ID { get; set; }
    
        public virtual user_pets user_pets { get; set; }
        public virtual vets vets { get; set; }
        public virtual vaccine_status vaccine_status1 { get; set; }
    }
}
