//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petscare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vets_adress
    {
        public int vets_adressID { get; set; }
        public string vets_country { get; set; }
        public string vets_province { get; set; }
        public string vets_adress1 { get; set; }
        public string vets_postcode { get; set; }
        public Nullable<int> vets_ID { get; set; }
    
        public virtual vets vets { get; set; }
    }
}
